### ISSUE TITLE
Series S60 3rd Edition (S60v3 aka Symbian 9.2) support

### ISSUE THREAD

**Issue by ghost** [fedor4ever/GCCE4Symbian#1]

**Comment by fedor4ever** [comment]
It already support 9.1+. Fixing sdk out of scope. You can fix your sdk as I did.

**Comment by ghost** [comment]
Can you give some instruction for use it with this SDK
- https://cloud.mail.ru/public/JxE5/CDr4AStEZ
- https://github.com/mstorsjo/gnupoc-package

**Comment by fedor4ever** [comment]
Do you have problems with my toolchain? Install, try, then ask if you have problems.

**Comment by ghost** [comment]
@fedor4ever, I have few question Symbian-related. How I can contact with you via email?

**Comment by fedor4ever** [comment]
I was ill. Sorry for long waiting. My mail - my git nick, then mail sign with string list.ru.

> Панядзелак, 24 кастрычніка 2016, 9:56 +03:00 ад AppSoft4 notifications@github.com:
> 
> @fedor4ever , I have few question Symbian-related. How I can contact with you via email?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly,  view it on GitHub , or  mute the thread .

Stryzhniou Fiodar
Стрижнёв Федор
