### ISSUE TITLE
Compiling with MinGW

### ISSUE THREAD

**Issue by DenisShulzhenko** [fedor4ever/GCCE4Symbian#2]
I'm trying to build Symbian GCC 5.5.0 with yours script by MSYS and GCC 6.3.0-1 on Windows 7 for Qt Creator. But every time get errors like: 
/bin/sh: line 3: cd: ./libcc1: No such file or directory
or
/bin/sh: line 3: cd: arm-none-symbianelf/libstdc++-v3: No such file or directory
and then building gcc crashes.

**Comment by fedor4ever** [comment]
What print gcc -v? g ++ -v? post full log here.
Fiodar Stryzhniou

исходное сбщ
Тема: [fedor4ever/GCC-4-Symbian] Compiling with MinGW (#2)
От: Denis Shulzhenko <notifications@github.com>
Дата: 16.05.2018 21.05

I'm trying to build Symbian GCC 5.5.0 with yours script by MSYS and GCC 6.3.0-1 on Windows 7 for Qt Creator. But every time get errors like: 
/bin/sh: line 3: cd: ./libcc1: No such file or directory
or
/bin/sh: line 3: cd: arm-none-symbianelf/libstdc++-v3: No such file or directory
and then building gcc crashes.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/fedor4ever/GCC-4-Symbian/issues/2

**Comment by DenisShulzhenko** [comment]
`$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=m
ingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-i
sl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=
generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='Min
GW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwar
f2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libic
onv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable
-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)`
`$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\g++.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=m
ingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw
--prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --ena
ble-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.
3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-
sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/m
ingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic -
-enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)`
[make-gcc.log](https://github.com/fedor4ever/GCC-4-Symbian/files/2012838/make-gcc.log)
[config.log](https://github.com/fedor4ever/GCC-4-Symbian/files/2012846/config.log)

**Comment by fedor4ever** [comment]
I build Symbian GCC with MSYS and GCC 5.3.0 by build-toolchain.sh.

I look at make-gcc.log in my gcc build directory:
- make-gcc.log from mine gcc build have  599 kylobytes and 8220 lines
- config.log.log from mine gcc build equal to yours

Check maybe you already build it? =)

Hints:
1. remove build-gcc dir
2. switch back to 5.3.0
3. check if arm-none-symbianelf-ld.exe exist in *:\MinGW\msys\1.0\local\gcc-5.4.0\bin
4. Reboot your pc and start again

If nothing helps - ask in gcc-help mail list. I subscribed there.

I have no idea how fix your  problem.

My files:
[make-gcc.log](https://github.com/fedor4ever/GCC-4-Symbian/files/2014283/make-gcc.log)
[config.log](https://github.com/fedor4ever/GCC-4-Symbian/files/2014285/config.log)

**Comment by fedor4ever** [comment]
Do you suceeded?

**Comment by DenisShulzhenko** [comment]
Yes, i dont know what was wrong (logs always was different, maybe hardware problem). I tried build it on another PC whith the same MinGW and GCC verdions by build-toolchain.sh and it was resolve the problem. Anyway thanks for help!

**Comment by fedor4ever** [comment]
Glad to hear that!
Look at my another project - port of elf2e32. Any tests or code review velcome =)
